In [1]:
import pandas as pd
import numpy as np

people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com',
              'JohnDoe@email.com', None, np.nan, None, 'Missing'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

df=pd.DataFrame(people)

In [28]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True   True   True
6  False  False  False  False

In [ ]:
#Display all missing values
df.fillna('Missing')

     first     last                    email      age
0    Corey  Schafer  CoreyMSchafer@gmail.com       33
1     Jane      Doe        JaneDoe@email.com       55
2     John      Doe        JohnDoe@email.com       63
3    Chris  Schafer                  Missing       36
4  Missing  Missing                  Missing  Missing
5  Missing  Missing                  Missing  Missing
6       NA  Missing                  Missing  Missing

In [7]:
#Count the number of missing values in each column.
df.isnull().sum()

first    2
last     2
email    3
age      2
dtype: int64

In [9]:
#Count the total number of missing values in the entire DataFrame.
df.isna().sum().sum()

9

In [20]:
#Show only rows that contain at least one missing value.
df.isna().any()

first    True
last     True
email    True
age      True
dtype: bool

In [ ]:
#Show only rows with no missing values.
df.isna().any(axis=1)

   first     last email   age
3  Chris  Schafer  None    36
4    NaN      NaN   NaN  None
5   None      NaN  None  None